from bot.models.entities import (
    Faculty,
    Group,
    GroupSubject,
    Role,
    ScheduleBinding,
    ScheduleEntry,
    ScheduleLessonType,
    ScheduleNotificationLog,
    ScheduleTemplate,
    ScheduleWeekType,
    Student,
    Subject,
    SubjectKind,
    SubjectWork,
    Submission,
    User,
)

__all__ = [
    "Faculty",
    "Group",
    "GroupSubject",
    "Role",
    "ScheduleBinding",
    "ScheduleEntry",
    "ScheduleLessonType",
    "ScheduleNotificationLog",
    "ScheduleTemplate",
    "ScheduleWeekType",
    "Student",
    "Subject",
    "SubjectKind",
    "SubjectWork",
    "Submission",
    "User",
]
